index:
    path: /
    defaults: { _controller: 'App\Controller\LouvreController::index' }

informations:
    path: /informations
    defaults: { _controller: 'App\Controller\LouvreController::informations' }